hw_1: add solution
danilkladnitsky/nlp-tasks pull request #1
Opened 2023-09-26 17:51 UTC by danilkladnitsky

2023-09-26 20:25 UTC, danilkladnitsky commented
@pacifikus, Добрый день!
Простите за мусорные коммиты в этой ветке, тестировал автосборку и деплой notebook-а: https://danilkladnitsky.github.io/nlp-tasks/hw_1/

2023-10-03 22:58 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! Выглядит здорово, особенно ноутбук на github.io :)

- Импорты лучше все же располагать в начале ноутбука, примерно как в .py скриптах
- По заданию нужно было взять датасет из _corus_, но, думаю, вы с этим без проблем справились бы, так что и данные из `nltk `подойдут

2023-10-06 17:25 UTC, danilkladnitsky commented
> Добрый день!
> 
> Спасибо за работу! Выглядит здорово, особенно ноутбук на github.io :)
> 
> * Импорты лучше все же располагать в начале ноутбука, примерно как в .py скриптах
> * По заданию нужно было взять датасет из _corus_, но, думаю, вы с этим без проблем справились бы, так что и данные из `nltk `подойдут

Перенес импорты)

2023-10-07 00:34 UTC, pacifikus approved these changes
LGTM

2023-10-07 13:07 UTC, merged