hw_2: add solution
danilkladnitsky/nlp-tasks pull request #2
Opened 2023-10-07 15:39 UTC by danilkladnitsky

2023-10-16 19:16 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! В целом все хорошо, но есть некоторые моменты, которые можно улучшить:
- Для предотвращения лика пайплайн применения `CountVectorizer` и некоторых других трансформаций выглядит как "разбиение на train/test -> обучаем трансформер на train -> применяем к test". поэтому у вас должна немного поменяться логика классов и их взаимодействия. Сейчас в _NaiveBayes approach_, _DecisionTreeClassifier approach_ модели учатся на всем наборе данных `df['email']`
- Не совсем понятна логика работы в классах с атрибутами класса и объекта, например, в `Vector` задается `vectorizeMethod = CountVectorizer()`, а потом в метод инициализации приходит `method` и уже задается переменная экземпляра `self.vectorizeMethod = method`.
При этом атрибуты уровня класса являются общими для всех объектов класса, но, как будто, у вас нигде не задействуются. На всякий случай приведу пример:
![image](https://github.com/danilkladnitsky/nlp-tasks/assets/22592039/3cee0a66-602b-4726-ba11-cd8fe1ba9d10)

- Не очень понятно, зачем нужен класс `FitModelIml`. Можно методы напрямую реализовывать в потомках. Такие классы могут иметь смысл, если использовать их в качестве абстрактных классов, а не в середине дерева наследования: [Abstract Base Class](https://peps.python.org/pep-3119/)
- Ну и в целом для кастомных моделей удобнее наследоваться от `sklearn.base.BaseEstimator` 
- Также не увидела подбор гиперпараметров

2023-10-18 13:20 UTC, danilkladnitsky commented
@pacifikus 
Добрый день! 
Пофиксил проблему с train/test data, порефакторил чуть код - решил убрать свой бессмысленный и ужасный ООП (но претензии к нему прочитал и осознал, спасибо!).

Правда не совсем понял, что значит "Для предотвращения лика пайплайн применения". Попробовал погуглить термин, нашел Data Leakage in pipeline (https://medium.com/@wing.y.tse.jobs/a-step-by-step-guide-to-avoid-data-leakage-by-pipeline-randomizedsearchcv-and-votingregressor-in-68b01aca6109). 
Это оно?)

2023-10-24 20:17 UTC, pacifikus requested changes
Добрый день!

Все выглядит значительно лучше, пока только не увидела подбор гиперпараметров моделей.

По поводу лика в данных (утечки) - здесь я имела в ввиду утечку данных о тестовом датасете в тренировочную часть, тогда метрики у модели могут получиться хорошими, но  обобщающая способность будет низкая.

Вот хорошая статья про эту проблему, и как ее можно избежать: https://habr.com/ru/companies/vk/articles/746360/

2023-10-30 20:30 UTC, danilkladnitsky commented
@pacifikus 
Добрый день!
Добавил подбор гиперпараметров через GridsearchCV

2023-11-10 20:25 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу! Все выглядит отлично, только упомяну, что после подбора гиперпараметров не обязательно переобучать лучший вариант:
```
nb = grid_search.best_estimator_.fit(countVect_x_train, y_train)
pred = nb.predict(countVect_x_test)
```
лучший вариант модели и так содержится в `grid_search.best_estimator_`, так как по умолчанию у `GridSearchCV` задан аргумент `refit=True`, который отвечает за финальное переобучение модели с лучшими гиперпараметрами

2023-11-10 21:00 UTC, merged