hw_3
danilkladnitsky/nlp-tasks pull request #3
Opened 2023-10-23 16:56 UTC by danilkladnitsky

2023-10-25 13:44 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! Все выглядит отлично!

Небольшой комментарий: здесь примерно та же история, что и в случае CountVectorizer, мы делим выборку на train/test, обучаем модель векторизации на train, получаем с ее помощью эмбеддинги для train/test, и на train учим уже модель классификации, применяя ее потом к test. То есть не нужно делать новый сплит перед применением `LogisticRegression`

2023-10-30 19:00 UTC, danilkladnitsky commented
@pacifikus 
Добрый день!
Поправил последнее замечание. Как я понял, раз мы сравниваем два способа создать эмбеддинги для слов, то объективнее датасет один раз "сплитнуть", скормить библиотекам одни и те же train и test данные и уже сравнивать полученную точность на выходе.

2023-11-10 20:26 UTC, pacifikus commented
> @pacifikus Добрый день! Поправил последнее замечание. Как я понял, раз мы сравниваем два способа создать эмбеддинги для слов, то объективнее датасет один раз "сплитнуть", скормить библиотекам одни и те же train и test данные и уже сравнивать полученную точность на выходе.

Добрый день!

Да, все верно!

2023-11-10 20:30 UTC, pacifikus requested changes
В целом все выглядит отлично, но лучше пушить в гит ноутбуки без ошибок и закомментированного кода...

![image](https://github.com/danilkladnitsky/nlp-tasks/assets/22592039/b9d01922-61a1-44b7-a8de-309c73110ae3)

Если у вас есть код, который должен иногда отрабатывать, а иногда нет, то лучше его в `if-else` и гибко управлять выполнением кода, например,

```
need_preprocessing = False

if need_preprocessing:
    preprocess()
else:
    ...
```

2023-11-15 14:46 UTC, danilkladnitsky commented
@pacifikus 
Добрый день!
Убрал комментарии, скомпилировал ноутбук без ошибок: https://danilkladnitsky.github.io/nlp-tasks/hw_3/

2023-11-21 15:18 UTC, pacifikus approved these changes
LGTM

2023-11-28 09:58 UTC, merged